# Generated by Django 4.2 on 2023-05-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_rename_sale_product_supplier_alter_employee_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
